### ISSUE TITLE
Command's first block will contain all characters after its position

### ISSUE THREAD

**Issue by ianlucas** [ianlucas/mathjax-editor#1]
Value: `11|11`
After command insertion: `11\sqrt{|11}`
Expected: `11\sqrt{|}11`

**Comment by pkra** [comment]
Just wanted to let you know that this looks like a cool project. Glad to see you're making progress. If you need help with MathJax, drop us a line.

**Comment by ianlucas** [comment]
Hey Peter, thanks for the message! Where can I contact you guys? It would be cool to hear some tips on how I could have approached this editor. As for now, basically, the editor parses the Tex that the user put on it, and then it looks for the corresponding elements rendered by MathJax to make it interactive.

**Comment by pkra** [comment]
Probably the best place to start is our mailing list at http://groups.google.com/d/forum/mathjax-users. The development list at https://groups.google.com/d/forum/mathjax-dev as well but it's more for mathjax's own development (though it might be interesting especially with v3 being on the way).
