### ISSUE TITLE
Fixed equasion elements.

### ISSUE THREAD

**Issue by GarkGarcia** [ianlucas/mathjax-editor#33]
Hi there!
I'd like to know if there's any way to make a specific part of a displayed equation unchangeable while other parts remain editable... For example: the displayed equation follows the fixed ![codecogseqn](https://latex.codecogs.com/gif.latex?K%3D%5Csqrt%7Ba%5E2&plus;b%5E2%7D) model while the "a" and "b" coefficients are user controlled.
Thanks for the attention :)

**Comment by ianlucas** [comment]
Hey there, 

I'm gonna look at this and other features in April, I've been pretty busy lately!

Thanks for the input.

**Comment by ianlucas** [comment]
So, my latest commit 2ec1c22 addresses your request. I'm not going to make a build right now, maybe on this weekend, but you can build it by cloning the repo and running `yarn run build`.

Use the new option "readonly" as `true` to lock the equation, and add an `editable="true"` attribute to the `<mrow>` you want to make editable, like this: `editor.setValue('<math><mi>K</mi><mo>=</mo><msqrt><mrow><msup><mrow><mi>a</mi></mrow><mrow editable="true"><mn>2</mn></mrow></msup><mo>+</mo><msup><mrow><mi>b</mi></mrow><mrow editable="true"><mn>2</mn></mrow></msup></mrow></msqrt></math>')`. In this example, just the powers would be editable.

I'm thinking in adding some kind of filter, so you can allow just numbers as input on those editable elements.
