### ISSUE TITLE
Cursor not always in focus and in view

### ISSUE THREAD

**Issue by skhan02** [ianlucas/mathjax-editor#34]
I noticed that the cursor is not always in focus - i have overflow set to scroll on mathjax-editor-display. When i insert numbers the content grows to the left hence the cursor position is in view. However when i insert sqrt, fraction, superscript, subscript the display shows the initial position- the carot remains at the end though (which is correct). Any reason why the content displayed is the beginning of the expression? Thanks for your help in advance @ianlucas !

**Comment by ianlucas** [comment]
Sorry for the long delay, in the next days I will be deploying the v3 version of this project.

I hope the new version will fix this issue, please let me know if you encounter it again.
